version: '3.8'
services:
  jaeger-allinone:
    image: jaegertracing/all-in-one:1.34
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
  echo-app:
    image: 'echo-app:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - JAEGER_ENDPOINT=http://jaeger-allinone:14268/api/traces
